export const REGISTER_SUCESS='REGISTER_SUCESS'
export const REGISTER_FAIL='REGISTER_FAIL'

export const LOGIN_SUCESS='LOGIN_SUCESS'
export const LOGIN_FAIL='LOGIN_FAIL'

export const LOAD_USER_SUCESS='LOAD_USER_SUCESS'
export const LOAD_USER_FAIL='LOAD_USER_FAIL'

export const LOGOUT='LOGOUT'